#!/bin/bash

# copy sascfg_personal.py to default location
mkdir -p ~/.config/saspy/
cp ./binder/sascfg_personal.py ~/.config/saspy/


cd jlab_create_sas_file
pip install -e .
jupyter labextension develop . --overwrite

cd ../sas2nb
pip install -e .
jupyter labextension develop . --overwrite

cd ../sas_log_viewer
pip install -e .
jupyter labextension develop . --overwrite

jlpm run build
